### ISSUE TITLE
Are you competing in https://github.com/AmericaMakes/OASIS-Challenge-Baseline-Code-and-Models

### ISSUE THREAD

**Issue by harshilpatel1799** [drlukeparry/pyslm#1]
Are you competing in https://github.com/AmericaMakes/OASIS-Challenge-Baseline-Code-and-Models challenge. I am competing and have build a very similar program with different scan strategies and have build the output layer files very similar to yours but I am having difficulties converting it into the open-source XML format which can be used for laser fusion additive builds. I am looking actually looking to use the open-source XML format with a open source microcontroller that runs on LabView that takes in these files and build the machine build file. If you have any concern on copyright about using your codebase as inspiration, I can resolve that.

**Comment by drlukeparry** [comment]
I haven't entered because I am not affiliated with an AmericaMakes organization, nor has the competition organizers returned a reply to a previous query. 

The code has been released under a LGPL license, and ideas proposed on the blog are for other researchers to explore and develop further if they wish. It is at your discretion if you have used code directly to share any changes, which given the competition's requirements would be released opensource anyway. However,  I would appreciate any contributions  that can benefit other users or researchers or acknowledgement to PySLM. 

I am not aware of any SLM/SLS systems which use  XML for their build-files, so it doesn't present any intrinsic value to incorporate this into PySLM. I can discuss this offline if you are looking to develop a micro-controller. 

Kind Wishes,
Luke
