### ISSUE TITLE
.rdn format generation and reading build files

### ISSUE THREAD

**Issue by noedev86** [drlukeparry/pyslm#34]
Hi, 
I wanted to know if there is any python example code to read and compile a .rdn file from Realizer, as well as the .rea file format. I only saw the .mtt format available.
Thank you

**Comment by drlukeparry** [comment]
Hi,

The older Realizer .rea file format is supported in libSLM, but I have not fully tested this recently. This has been superceded by the modern version apparently adopted by DMGMori, however, I don't have access to any of these files. The .rdn file from what I understand is a similar construct ot the .rea format but with additional metadata.

**Comment by noedev86** [comment]
and how did you do it for the .rea file? did the company give you some sort of library of any sort to help you compile it ? Because I'm working on this and it seems that you need a part of the code in order to compile it in their format.

**Comment by drlukeparry** [comment]
The .rea file format specification or supporting library was unavailable and also was not provided by Realiser GmbH at the time. Therefore I had to reverse engineer the file format accordingly. As a result, access to the translator is only for research purposes because licensing agreement with the company is likely be required.
