### ISSUE TITLE
Improper array size error in identifysupportregions

### ISSUE THREAD

**Issue by invalidflaw** [drlukeparry/pyslm#38]
While attempting to generate support material for a part, I receive the following error. It seems to be an array size mismatch, but I am unsure of the current cause.

![image](https://github.com/drlukeparry/pyslm/assets/36581852/fe9cd606-f53c-474a-974e-9202d661bfb6)

**Comment by drlukeparry** [comment]
This sometimes happens when the identified overhang boundaries extend beyond the overhang surface of the mesh , therefore when the points are re-projected back, they do not entirely intersect with the original mesh. 

You can attempt to decrease the BlockSupportGenerator.rayProjectionResolution attribute to lower value e.g. 0.1

Alternatively, you can increase the boundary offset parameter to increase the likelihood the project points intersect with the mesh:

BlockSupportGenerator.rayProjectionResolution._outerSupportEdgeGap

I shall try to raise an automatic error message when this happens in the future. 

Let me know if you cannot resolve this. 

Luke
