### ISSUE TITLE
missing for example_support_structure.py

### ISSUE THREAD

**Issue by quentinodigiminlabs** [drlukeparry/pyslm#42]
Hi there,

I cannot find the file bracket.stl used in the example for support structure generation. Where should I find it ?

thanks,

Quentin

**Comment by drlukeparry** [comment]
Dear Quentin,

The bracket.stl model was found on the a repository  for the [GrabCAD Aerospace Bracket Challenge ](https://grabcad.com/challenges/airplane-bearing-bracket-challenge) - I cannot recall which model it is but attached is for reference.

[bracket.stl.zip](https://github.com/drlukeparry/pyslm/files/14351554/bracket.stl.zip)

 I don't include this because there I don't know the licensing for the original file to distribute this publicly.

In the future I will change PySLM to an include a separate mesh file for the support generation example  in the main release. 

Kind Wishes,
Luke
