### ISSUE TITLE
Multi-Laser Path Planning?

### ISSUE THREAD

**Issue by ohararp** [drlukeparry/pyslm#48]
Luke,

1. Thanks again for this great body of work!
2. I am working on a problem related to multi-laser time estimates:
a. It's not clear but do you have any example of doing path planning for 4 or 12 laser systems?
3. If not, I was considering an approach whereby we would take a build layout stl and boolean intersecting with a scan zone and then doing individual time estimates on each stl. This seems a bit of brute force and would not account for zone overlaps. I am hoping there may be a more elegant solution within pyslm's capabilities.

Ryan

**Comment by drlukeparry** [comment]
Hi Ryan,

I currently do not have any examples of multi-laser scanning, mainly because of the lack of consistency between systems and no agreed standard (both industrially and academically). Also I had previous limitations getting access to a capable system. Only recently at Nottingham, we have a multi-laser source Aconity Midi system, therefore we can at some point explore this functionality. So far I only know that the Renishaw _.mtt_ formats explicitly describe which LayerGeometry group that are scanned by each laser on their quad-laser L-PBF system, but I am unsure whether this capability is definable by the user across other L-PBF systems. With the highest-level of control, each LayerGeometry group could be assigned to a separate laser and run in-parallel assuming no timing delays.

The scan-vectors deployed across these systems may not be faithful to those provided in the build-file. This will entirely depends on the order of timings between scan vectors, and if the lasers can fully scan concurrently or in a sequential, or there is internal logic that pre-process the scan-vectors across to run in particular order. Perhaps, this does not matter too much at this stage.

#3 - This is is the simplest approach, but you'd need to ensure there were sufficient overlap between regions (risky). I would attempt the distribution of scan-vectors between lasers at a slice level, which can also be performed in parallel. You could isolate within a layer discrete closed polygons, and within each region divide the region into stripes/islands for scanning separately with the different lasers. These separate stripe regions an be offset/expanded to ensure that there is sufficient coverage. All of this has to take into account for spatter plumes produced by each laser, but also prevent localised overheating. 

It is not a trivial process to perfect, but with some optimisation algorithm with a combination of some cost functions the distribution of scan vectors between multiple lasers could be likely improved further

**Comment by ohararp** [comment]
Luke, great summary!  Thank you for confirming status and some options to consider.  It's been awhile but, Aconity definitely had a relatively simple CLI+ format that looked quite handy for multi-laser path planning.
